NCAR/ccpp-framework

- schemes/parse_scheme_table.py
- to allow for multiple modules within each file; allows subroutines other than _init, _run, _finalize
> update parse_scheme_table.py 

- LICENSE
> Add a license file - Apache V2.0

- examples/suite_scm_GFS_test.xml
- scripts/ccpp_prebuild_config_SCM.py
point to ccppphys lib in SDF; change paths to physics schemes in prebuild config for SCM
> updates necessary after repo name change

- scripts/ccpp_prebuild_config_SCM.py
This PR updates scripts/ccpp_prebuild_config_SCM.py to reflect the latest directory/repository name changes for running SCM+CCPP.
> Update of ccpp prebuild config

- doc/UsersGuide/SCM/chap_install.tex
- doc/UsersGuide/SCM/chap_intro.tex
- doc/UsersGuide/SCM/chap_run.tex
- doc/UsersGuide/SCM/title.tex
Updates to the title of users guide so it is a guide to Bundle CCPP plus SCM (not just SCM or just CCPP).
Miscellaneous updates throughout Users Guide.
Also needs to be merged into feature/ipd-setup-step-fast
> Updates to the title of users guide

- doc/DevelopersGuide/chap_schemes.tex
- doc/DevelopersGuide/main.tex
- doc/DevelopersGuide/title.tex
- doc/common/gmtb.sty
Description to come after lunch break.
> Minor formatting changes in gmtb.sty and Developers' Guide

- examples/suite_GFS_operational_2017_scm.xml
- examples/suite_GFS_operational_2017_scm_prescribed_surface.xml
Changed name of SDFs that work with SCM to remove "test". This PR works with one for the SCM.
> Sdf name change

- examples/suite_GFS_operational_2017.xml
- examples/suite_scm_GFS_test.xml
- examples/suite_scm_GFS_test_prescribed_surface.xml
- scripts/ccpp_prebuild_config_FV3.py
- scripts/metadata_parser.py
changes in ccpp-framework associated with updating hybrid EDMF scheme; changed name of scheme in SDFs to match code; uncommented scheme and dependencies in ccpp_prebuild config for FV3 (note: have not changed mfpbl.f code yet -- just uncommented to work on moninedmf.f)
> Moninedmf update

- examples/suite_FV3_test.xml
- examples/suite_FV3_test_gfdlmp.xml
- scripts/ccpp_prebuild_config_FV3.py
See https://github.com/NCAR/ccpp-physics/pull/126 for a full description of these changes.
> Gfs_calpreciptype interstitial update

- examples/suite_FV3_test.xml
- examples/suite_FV3_test_gfdlmp.xml
- scripts/ccpp_prebuild_config_FV3.py
See https://github.com/NCAR/FV3/pull/38 for a full description.
> GFS_stochastics CCPP compliant

- examples/suite_FV3_test.xml
- examples/suite_FV3_test_gfdlmp.xml
- examples/suite_GFS_operational_2017.xml
- examples/suite_GFS_operational_2017_scm.xml
- examples/suite_GFS_operational_2017_scm_prescribed_surface.xml
- scripts/ccpp_prebuild_config_FV3.py
adding in GFS_PBL_generic_pre/post into SDFs and adding to FV3 prebuild configuration for parsing
> PBL_interstitial_update

- examples/suite_FV3_test.xml
- examples/suite_FV3_test_gfdlmp.xml
- scripts/ccpp_prebuild_config_FV3.py
- src/ccpp_fields_idx.h
- src/ccpp_memory.c
See https://github.com/NCAR/FV3/pull/48 for a detailed description.
> stochastic_physics in GFS_time_vary_step CCPP-compliant

- examples/suite_FV3_test.xml
- examples/suite_FV3_test_gfdlmp.xml
- scripts/ccpp_prebuild_config_FV3.py
updates to existing SDFs to call GFS_surface_generic_pre/post and to compile the file with the rest of CCPP
> GFS_surface_generic update

- scripts/ccpp_prebuild_config_SCM.py
- suites/suite_SCM_GFS_2018_updated.xml
- suites/suite_SCM_GFS_2018_updated_prescribed_surface.xml
added GFDL MP source to ccpp_prebuild; added 2 suites (one full, one prescribed surface) that use GFDL MP
> GFDL MP to SCM

- .travis.yml
Fix previously broken automatic testing with Travis on MacOSX
> Travis testing with MacOSX

- CMakeLists.txt
- scripts/ccpp_prebuild.py
- scripts/ccpp_prebuild_config_FV3.py
- scripts/ccpp_prebuild_config_SCM.py
- scripts/ccpp_prebuild_config_TEST.py
- scripts/common.py
- scripts/mkcap.py
- scripts/mkstatic.py
- src/CMakeLists.txt
- src/ccpp_fields.F90
- src/ccpp_suite.F90
- src/ccpp_types.F90
- suites/suite_FV3_GFS_2017_updated_test.xml
See https://github.com/NCAR/FV3/pull/80 for a description.
> CCPP static build

- suites/suite_FV3_CPT_adv.xml
- suites/suite_SCM_CPT_adv.xml
See https://github.com/NCAR/NEMSfv3gfs/pull/58 for a description.
> SHOC follow-up: fix test setup

- scripts/ccpp_prebuild_config_FV3.py
- scripts/ccpp_prebuild_config_SCM.py
- src/ccpp_fields_idx.h
See https://github.com/NCAR/NEMSfv3gfs/pull/64 for a description.
> Merge VLAB master into GitHub CCPP branches 2018/10/18

- suites/suite_FV3_GFS_2017_updated_gf_gfdlmp.xml
- suites/suite_FV3_GFS_2017_updated_gf_thompson.xml
This PR adds new suite definition files for running the Grell-Freitas convection scheme with the GFDL cloud microphysics scheme or the Thompson microphysics scheme.
> "Add new SDFs for GF with gfdlmp and thompson"

- doc/DevelopersGuide/scheme_template.F90
Updated standard_name and long_name for errmsg and errflg for documentation.
> Update standard_name and long_name for errmsg and errflg.

- CODEOWNERS
> Add Steve Goldhaber (gold2718) to CODEOWNERS

- scripts/metadata_parser.py
This PR enables parsing additional Fortran type definitions of kind
```
type, extends(foo) :: bar
```
with the existing `ccpp_prebuild.py`/`metadata_parser.py` scripts. The workaround triggers only for type definitions that start with `type` or `type,` and contain the word `extends`. It uses the class routine of the class `Ftype_type_decl` introduced by the new metadata parser (i.e. `cap_gen`'s metadata parser). This limited implementation is used to make sure that none of the other logic in `metadata_parser.py` is broken.
I tested this by replacing the following entry in `GFS_typedefs.F90`
```
#ifdef CCPP
type GFS_data_type
type(GFS_statein_type)  :: Statein
type(GFS_stateout_type) :: Stateout
type(GFS_sfcprop_type)  :: Sfcprop
type(GFS_coupling_type) :: Coupling
type(GFS_grid_type) …
```
> Workaround to parse additional Fortran type definitions using ccpp_prebuild.py

- scripts/metadata_parser.py
This PR updates scripts/metadata_parser.py: rework logic for detecting Fortran derived type definitions, use new Ftype_type_decl class, routine type_def_line after filtering all invalid/other cases. Slightly improved documentation in form of comments.
This has been tested with NEMSfv3gfs to compile on Theia/Intel in standalone/dynamic mode (i.e. all parameterizations are included) and on MacOSX/GNU to compile and run (with bit for bit identical results) in all possible modes hybrid/standalone/static.
Additional type definitions were added to test the new logic:
```
type, public :: mytype
type, extends(foo) :: bar
type myothertype
type :: yetanothertype
```
This PR can be merged w/o running the regression tests, but I'd appreciate if someone (@grantfirl?) was able to test it with SCM.
> Update logic to parse Fortran type definitons (ccpp_prebuild version, again!)

- scripts/convert_metadata.py
- scripts/parse_tools/preprocess.py
- src/ccpp_fcall.F90
See https://github.com/NCAR/NEMSfv3gfs/pull/162 for a description.
> Remove CCPP HYBRID mode

- doc/CCPPtechnical/source/ConstructingSuite.rst
Documentation change only
`doc/CCPPtechnical/source/ConstructingSuite.rst`: remove references to `sfc_sice_post`
> CCPP GitHub update from VLab master 2019/06/11

- doc/CCPPtechnical/source/CompliantPhysicsParams.rst
- doc/DevelopersGuide/scheme_template.F90
- doc/DevelopersGuide/scheme_template.meta
This PR updates part of the Technical Documentation to reflect the new metadata format. Changes to the modified files are complete, please review. After you provide feedback, I will complete the changes to remaining parts of the document.
> Updates to Technical Documentation for new metadata format

- CMakeLists.txt
- update version number from 3.0.0 to 4.0.0
- update author list in CMakeLists.txt
> ufs_public_release: update version number and authors

- scripts/ccpp_datafile.py
- scripts/ccpp_fortran_to_metadata.py
- scripts/ccpp_suite.py
- scripts/host_model.py
- scripts/metavar.py
- test/capgen_test/run_test
- test/capgen_test/temp_adjust.F90
- test/capgen_test/temp_calc_adjust.F90
- test/capgen_test/temp_calc_adjust.meta
- test/capgen_test/temp_set.F90
- test/capgen_test/temp_set.meta
- test/capgen_test/test_host.F90
- test/capgen_test/test_reports.py
- Fix issue with how capgen handles the intent of CCPP suite CAP entry points
- Improve error message for bad host model table type.
- Create tests for post-capgen database reports
- Create and improve tests for run time inspection routines
fixes #279
Test with unit tests (python test/unit_tests/test_metadata_table.py) and capgen test (capgen_test/run_test)
> Bug fixes and more reports

- test/unit_tests/test_metadata_scheme_file.py
- test/unit_tests/test_metadata_table.py
Your code has been rated at 10.00/10
Both tests pass.
> Modifications to capgen unit tests to get perfect pylint rating

- scripts/ccpp_prebuild.py
- scripts/conversion_tools/unit_conversion.py
- scripts/metadata2html.py
- scripts/mkcap.py
Update dtc/develop from NCAR master 2020/07/21. Changes in this PR:
- Python updates
- Additional unit conversions
https://github.com/NCAR/GFDL_atmos_cubed_sphere/pull/16
https://github.com/NCAR/ccpp-framework/pull/313
https://github.com/NCAR/ccpp-physics/pull/479
https://github.com/NCAR/fv3atm/pull/61
https://github.com/NCAR/ufs-weather-model/pull/62
For regression testing, see https://github.com/NCAR/ufs-weather-model/pull/62.
> Update dtc/develop from NCAR master 2020/07/21

- scripts/metadata_table.py
- test/run_doctest.sh
- test/unit_tests/sample_files/test_dependencies_rel_path.meta
- test/unit_tests/test_metadata_table.py
Fix parsing of dependencies with extra commas
Added unit test to make sure it works correctly
Fixes #385
> Fix parsing of dependencies
