NCAR/ccpp-framework

.gitignore
schemes/common.py
schemes/longnames_autocheck.py
schemes/parse_fortran.py
schemes/parse_scheme_table.py
schemes/process_tables.py

New script that employs existing scripts (parse_scheme_table.py, process_tables.py) to automatically check out gmtb-ccpp repositories from defined separators and search for longname conflicts. Includes the possibility to use existing (i.e. once checked out and corrected manually) repositories on a per-separator basis in case modifications are necessary for the script to proceed.

Longname conflict checker

---

CMakeLists.txt
schemes/check/CMakeLists.txt
schemes/scm/CMakeLists.txt
src/CMakeLists.txt

Older versions of cmake insert a compiler flag -i_dynamic for Intel compilers when creating shared libraries. This flag is deprecated and leads to a warning issued during compiling/linking. It does not necessarily lead to an error, but to be on the safe side and safe users from a confusing warning message, the deprecated compiler flag is replaced with the correct version -shared-intel in the CMakeLists.txt files.

Replace deprecated compiler flag for Intel compilers

---

src/ccpp_dl.c

This PR enables support for (reasonably recent) GNU compilers gcc+gfortran on Theia and Cheyenne, as well as for clang+gfortran on MacOSX. The only change required here is the different names of shared libraries and the order of suffix and version string on MacOSX.

Gmtb ccpp gnu support

---

examples/suite_GFS_operational_2017.xml
scripts/ccpp_prebuild.py
scripts/metadata_parser.py

This PR adds the necessary changes on the gmtb-ccpp side for adjusting module names and scheme names. It also includes a change to the ccpp_prebuild.py script to abort if module names and scheme names do not match.

Match module names and scheme names

---

README.md
schemes/check/check_noop.f90
schemes/check/nan.f90
schemes/mkcap.py
schemes/parse_scheme_table.py
scripts/ccpp_prebuild.py
scripts/common.py
scripts/metadata_parser.py
scripts/mkcap.py
src/ccpp_dl.c
src/ccpp_fields.F90
src/ccpp_strings.F90
src/tests/test_check.f90

This PR performs cleanup work and adds support for correct error handling in physics schemes.
Cleanup work includes:
- renaming of metadata columns
- renaming of ccpp_fields_{add,get} to ccpp_field_{add,get}
- improvements to Python scripts
- formatting changes
Support for error handling in physics schemes includes:
- additional routines for storing and retrieving character(len=XYZ) variables in/from the cdata structure
- converting scheme caps into functions, returning an error code of type c_int32_t to the C interface
- an error code other than 0 forces CCPP to return immediately with the same error code to the host model
The changes have been tested for b4b identical results on Cheyenne and MacOSX systems. On Theia with Intel 18, the results are different because of a problem …

gmtb-ccpp cleanup and error handling

---

scripts/mkcap.py
src/ccpp.F90
src/ccpp_fields_idx.c
src/ccpp_fields_idx.h
src/ccpp_suite.F90
src/ccpp_types.F90

This PR improves the performance of the CCPP implementation in FV3 v0 by
- making use of threading (i.e. OpenMP parallel regions) where possible
- by adding functionality to the CCPP infrastructure that allows to copy an existing CCPP suite data structure from one cdata structure to another. An additional attribute iscopy is required for the CCPP suite data structure to distinguish between the original suite data type and its copy because of C-pointer types being used inside the data structure
- and by increasing the default size of the cdata field index array from 75 to 500 (currently about 400 fields are used in FV3)
The results are bit for bit compatible (tested on Theia/Intel and Macbook/GNU with OpenMP enabled).

gmtb-ccpp optimization: speedup of ccpp init

---

cmake/FindOpenMP_Fortran.cmake
schemes/CMakeLists.txt
scripts/ccpp_prebuild.py
scripts/ccpp_prebuild_config_FV3.py
scripts/ccpp_prebuild_config_SCM.py

This PR adds additional logic to handle different host models in the CCPP prebuild script:
- import Python module containing CCPP prebuild config based on variable HOST_MODEL set in ccpp_prebuild.py
- two configurations ccpp_prebuild_config_SCM.py and ccpp_prebuild_config_FV3.py
Also included are fixes for deprecated OpenMP compiler flags for the Intel compiler and the removal of unused code.

Scm integration fv3mods dom

---

.travis.yml
README.md
doc/UsersGuide/SCM/chap_run.tex
schemes/longnames_autocheck.py

This PR updates Python scripts and documentation to reflect repository name changes. Also included is to temporarily deactivate the travis continuous integration for MACOSX (broken since a while due to changes in brew/homebrew), but keeps the Linux config.

ccpp-framework repo name changes for fv3

---

schemes/check/CMakeLists.txt
src/CMakeLists.txt

This PR performs cleanup tasks: replace deprecated compiler flag -i_dynamic for Intel with -shared-intel.

ccpp-framework cleanup 20180402

---

doc/DevelopersGuide/chap_hostmodel.tex

Added a missing backslash whose absence caused an error condition during make.
Tested by running make in doc/DevelopersGuide directory.

DevelopersGuide bugfix

---

CMakeLists.txt
doc/CMakeLists.txt
examples/suite_FV3_test.xml
examples/suite_scm_GFS_test.xml
schemes/CMakeLists.txt
schemes/check/CMakeLists.txt
scripts/ccpp_prebuild.py
scripts/ccpp_prebuild_config_FV3v0.py
scripts/ccpp_prebuild_config_FV3v1.py
scripts/ccpp_prebuild_config_SCM.py
scripts/mkcap.py
src/CMakeLists.txt
src/ccpp.F90
src/ccpp_api.F90
src/ccpp_types.F90

This PR enables the integration of ccpp-framework (and ccpp-physics) in the current trunk of FV3 in directories ccpp/{framework,physics}.
Most changes are required for the build system so that it can be used with the existing SCM and with FV3 (current trunk). For the FV3-current trunk, the cmake configuration is cleaner and streamlined between the different CMakeLists.txt (and with ccpp-physics). To avoid introducing all these changes for SCM at the same time, the current - to be improved - cmake config for SCM is retained. A new variable PROJECT is introduced that allows to distinguish between different builds (currently 'CCPP-FV3' for FV3-current trunk and default='unknown' for SCM). The cmake build system needs to be reworked, best would be to introduce project 'CCPP-SCM' for the SCM …

Nemsfv3gfs master ccpp integration

---

examples/suite_FV3_test.xml
examples/suite_GFS_operational_2017.xml
examples/suite_scm_GFS_test.xml
schemes/check/check_test.f90
schemes/check/nan.f90
src/CMakeLists.txt
src/ccpp_dl.F90
src/ccpp_dl.c
src/ccpp_fcall.F90
src/ccpp_scheme.F90
src/ccpp_suite.F90
src/ccpp_types.F90

This PR separates out the changes to ccpp-framework in PR https://github.com/NCAR/ccpp-framework/pull/69 that enable running the XXX_init and XXX_finalize routines automatically for every scheme listed in the SDF.
In addition, a suite-specific scheme YYY can be used, for which the YYY_init and YYY_finalize routines can be run explicitly before (init) and after (finalize) the scheme init and finalize routines are run:
```
...
<init>YYY</init>
<group ...>
...
<scheme>XXX</scheme>
...
</group>
<finalize>YYY</finalize>
...
```
The above snippet will run:
- during init: YYY_init, XXX_init
- during the time integration: XXX_run
- during finalize: XXX_finalize, YYY_finalize
This PR was tested to work and is ready to review and merge.

CCPP run _init and _final for schemes

---

examples/suite_FV3_test.xml
scripts/ccpp_prebuild_config_FV3v1.py
src/ccpp_fcall.F90

This PR is one out of four (!) for NEMSfv3gfs and its submodules, ccpp-framework, ccpp-physics and FV3 that enables running the CCPP-compliant version of cnvc90 either directly from FV3/gfsphysics/physics (i.e. the current version in the FV3 trunk), or directly from ccpp/physics/physics (i.e. the CCPP-compliant version, but w/o using the CCPP framework), or via the CCPP-framework.
These three options exist for the Intel compiler only, for GNU and PGI, only the first and last options are available (i.e. cannot run the CCPP-compliant version without the CCPP framework).
Bit for bit tests:
- results are identical for the CCPP build compared to the standard, non-CCPP build for the two tests run (fv3_control and fv3_gfdlmp) on Theia+{Intel,GNU,PGI} and on MacOSX+GNU
- results are identical for …

Add CCPP-compliant CNVC90

---

CODEOWNERS

This PR adds a CODEOWNERS file for code owner review code protection. Currently only the GMTB folks, as soon as we have the official approval to work jointly on this with MMM and GCD, they will be added.

Code owner review code protection

---

scripts/mkcap.py
src/ccpp.F90
src/ccpp_fcall.F90
src/ccpp_fields.F90
src/ccpp_suite.F90
src/ccpp_types.F90

This PR contains improvements originally made for the GFDL MP fast physics processes, but applicable in general:
(1) Comparing the kind of variables between what is registered in cdata (i.e. provided by the host model) and declared in the cap (i.e. requested by the schemes).
(2) Fix of a previous implementation for handling multiple copies of suites: when using multiple cdata structures, a previous change introduced the possibility to make copies of a suite to avoid parsing the suite definition file (and loading the objects from the shared library) multiple times. This copying implied that multiple versions of the suite object existed in parallel, in sync only at the time the copy was made. This issue is fixed by using pointers instead of copies as introduced in this PR.
(3) Extending the …

Framework improvements: testing of variable kinds, handling of multiple suites

---

examples/suite_FV3_test.xml
scripts/ccpp_prebuild_config_FV3.py

Reverts NCAR/ccpp-framework#99 - current trunk is broken, results are no longer bit for bit identical on MacOSX+GNU and code hangs or crashed on Theia+Intel. Removing this PR and the associated PRs for FV3 and ccpp-physics fixes the issue.

Revert "update for deep convection generic interstitials"

---

examples/suite_FV3_test_wsm6.xml

A new suite definitoon file examples/suite_FV3_test_wsm6.xml is added that does not contain any calls to zhao_carr physics or interstitials. The WSM6 regression test was rerun to check for bit-for-bit reproducibility on Theia/Intel (the ldiag3d test was not run, because this one does not give bit for bit identical results anyway).
This PR is related to https://github.com/NCAR/NEMSfv3gfs/pull/31, which updates the test configurations fv3_ccpp_wsm6 and fv3_ccpp_wsm6_ldiag3d.

New SDF for WSM6 microphysics

---

examples/suite_FV3_test_gfdlmp.xml
examples/suite_FV3_test_wsm6.xml
scripts/ccpp_prebuild_config_SCM.py

This PR makes some follow-up adjustments for SCM after the VLAB master merge for NEMSfv3gfs went in.
For ccpp-framework: add h2ophys to CCPP prebuild config (even though not yet executed, but to make sure all the required variables and their metadata are available).

VLAB master merge follow-up for SCM 08/15/2018

---

examples/suite_FV3_test.xml
examples/suite_FV3_test_gfdlmp.xml
examples/suite_FV3_test_h2ophys.xml
examples/suite_FV3_test_wsm6.xml
examples/suite_GFS_operational_2017_scm.xml
examples/suite_GFS_operational_2017_scm_prescribed_surface.xml
scripts/ccpp_prebuild_config_FV3.py
scripts/ccpp_prebuild_config_SCM.py

Add GFS_suite_interstitial_3 and 4 to SDFs; remove GFS_zhao_carr_pre and GFS_gfdlmp_pre (code is now in GFS_suite_interstitial_3); remove unnecessary interstitial schemes from ccpp_prebuild scripts

MP interstitial cleanup 3

---

examples/suite_FV3_test_memcheck.xml
scripts/ccpp_prebuild_config_FV3.py
src/ccpp_memory.c

This PR enables the memory checking utility for the CCPP build of NEMSfv3gfs. A new SDF is introduced based on the standard SDF (for the fv3_ccpp_control test etc). This SDF can also be used in the future to conduct SDF-only (i.e. pure CCPP) runs with memory testing.
This PR is related to other PRs listed below. For information about regression testing and merging, see https://github.com/NCAR/NEMSfv3gfs/pull/35.

Memory checking utility for CCPP builds (of NEMSfv3gfs)

---

scripts/ccpp_prebuild.py
scripts/ccpp_prebuild_config_FV3.py
scripts/ccpp_prebuild_config_SCM.py
scripts/ccpp_prebuild_config_TEST.py
scripts/metadata_parser.py
scripts/mkdoc.py

In the CCPP prebuild scripts, the word category was used thus far to allow splitting physics schemes between different parts of the model code (e.g. slow_physics, fast_physics). As @ligiabernardet said, this is confusing, because people think of categories such as "microphysics", "PBL" etc. first.
We agreed to rename category to set (categories to sets); however, set is a reserved word in Python and as such pset (= physics set) is used in the scripts, the "documentation" and log output uses "physics set".
The correct functioning of the prebuild scripts was tested with SCM and FV3. I ran test cases for both to make sure that the output is still bit for bit identical. I also tested that the auto-generated LaTeX and HTML output of variables provided/requested is still correct.
As announced …

Update CCPP prebuild scripts and configs (category/categories -> set/sets)

---

suites/suite_FV3_GFS_2017_updated.xml
suites/suite_FV3_GFS_2017_updated_gfdlmp.xml
suites/suite_FV3_GFS_2017_updated_h2ophys.xml
suites/suite_FV3_GFS_2017_updated_memcheck.xml
suites/suite_FV3_GFS_2017_updated_wsm6.xml

This PR, together with those listed below, performs some final cleanup of the interstitial code in GFS_physics_driver.
For ccpp-framework: Update SDFs for FV3: add scheme GFS_stateout_update, remove comments; suite memcheck: add missing scheme MP_generic_pre
For details, see https://github.com/NCAR/FV3/pull/67

NEMSfv3gfs - final cleanup of interstitial code

---

scripts/ccpp_prebuild_config_FV3.py
scripts/ccpp_prebuild_config_SCM.py
src/ccpp_fcall.F90
suites/suite_FV3_GFS_2017_updated.xml
suites/suite_FV3_GFS_2017_updated_gfdlmp.xml
suites/suite_FV3_GFS_2017_updated_h2ophys.xml
suites/suite_FV3_GFS_2017_updated_memcheck.xml
suites/suite_FV3_GFS_2017_updated_wsm6.xml
suites/suite_SCM_GFS_2017_updated.xml
suites/suite_SCM_GFS_2017_updated_prescribed_surface.xml
suites/suite_SCM_GFS_2018_updated.xml
suites/suite_SCM_GFS_2018_updated_prescribed_surface.xml

This PR and others listed below enable the "standalone" version of NEMSfv3gfs-CCPP, that is bypassing the remaining GFS physics driver and using the suite definition file only. Results are bit for bit identical between CCPP reference (Theia/Intel 18 without CCPP), CCPP hybrid and CCPP standalone for the tests covered. Tests are also bit for bit identical for NEMSfv3gfs on MacOSX/GNU and for gmtb-scm on MacOSX/GNU.
Changes to ccpp-framework:
- add temporary logging capability to produce similar debugging output as for the CCPP hybrid code  (in GFS_physics_driver.F90) - only used if CCPP flag TEMPLOG is set
- add new scheme / source file sfc_diag_post.F90, clean up suite definition files

NEMSfv3gfs standalone CCPP runs

---

scripts/ccpp_prebuild_config_FV3.py
suites/suite_FV3_GFS_2017_updated_gfdlmp.xml

This PR and https://github.com/NCAR/FV3/pull/79 simplify the CCPP implementation of the fast physics processes in FV3. Essentially, the need to call fv_sat_adj_pre is removed, which leaves fv_sat_adj as the only scheme to run in group fast_physics. The changes to FV3 (https://github.com/NCAR/FV3/pull/79) move the resetting of the arrays from fv_sat_adj_pre back to dynamics (where they also happen for the non-CCPP build). I decided to not remove the file fv_sat_adj_pre.F90 from ccpp-physics yet and just comment out the line in ccpp_prebuild_config_FV3.py for the time being to remind us that this is needed in case it is not done elsewhere.
Results are bit for bit identical on MacOSX+GNU, the usual Theia/Intel tests are running. Regression test logs will be added once they finished. Feel …

Simplify GFDL MP fast physics

---

.travis.yml

Update .travis.yml to reenable Travis CI for MacOSX: use clang/clang++ instead of gcc/g++ to avoid errors for missing _stdio.h.

Work in progress - fix Travis CI for MacOSX

---

schemes/check/ccpp_prebuild_config.py
scripts/ccpp_prebuild.py
scripts/common.py
scripts/mkcap.py
scripts/mkstatic.py
src/ccpp_types.F90

This PR and associated PRs remove the need to store host model variables in the cdata structure and retrieve them in the physics for the static build only.
For this to work, and in the absence of a central host model registry in FV3, the following major changes are required:
- the auto-generated ccpp_static_api.F90 is no longer written to ccpp/physics/physics and compiled into the static CCPP physics library, but instead to FV3/gfsphysics/CCPP_layer and compiled with the host model
- the host model variables are imported in the ccpp_static_api module instead of being passed in via the argument list - this allows to maintain the same API for the static and dynamic builds
- in order to retrieve the correct block and thread number inside physics, these are now attributes of cdata (of type …

Static build: no cdata to store and retrieve variables

---

scripts/ccpp_prebuild.py
scripts/mkstatic.py

This PR addresses issue https://github.com/NCAR/ccpp-framework/issues/173
scripts/mkstatic.py and scripts/ccpp_prebuild.py: remove generating unnecessary include files for the static build (only required for dynamic build), remove dependency on ccpp_field_maps from static build
It is not required to make any changes to the FV3 host model cap files or to run the regression tests, since the #include statements are already ifdef-ed out for the static build. Compilation was tested for the non-CCPP, CCPP-hybrid, CCPP-standalone, CCPP-static-control and CCPP-static-gfdlmp builds.

Cleanup static build (CCPP prebuild version)

---

scripts/ccpp_prebuild.py

This PR fixes a bug in ccpp_prebuild.py where an exception is raised when trying to remove optional arguments from the argument list of modules that were filtered out for the static build. This PR is a prerequisite for https://github.com/NCAR/NEMSfv3gfs/pull/117 and associated PRs and is tested together with these (see https://github.com/NCAR/NEMSfv3gfs/pull/117 for the status of the regression tests).

ccpp_prebuild.py: bugfix when removing optional arguments

---

doc/DevelopersGuide/chap_schemes.tex
scripts/ccpp_prebuild.py
scripts/mkstatic.py
src/ccpp.F90
src/ccpp_suite.F90

This PR and associated PRs enable building the CCPP code in static mode and use multiple suites at the same time with the existing ccpp_prebuild.py script. This capability allows us to move forward with the discussion to remove the dynamic build options without having to move to the new metadata standard and to cap_gen and will save us valuable time for the transition in the future.
The changes are:
- a suite with name `XYZ` in the xml name attribute `<suite name='XYZ' ...> ... </suite>` must have the filename `suite_XYZ.xml`
- the `MAKEOPT` string `SUITE=suite_XYZ.xml` is replaced by `SUITES=XYZ,ABC,DEF`
- the `ccpp_suite` option in `input.nml` is now `ccpp_suite='XYZ'` to select suite `XYZ`
- in static build mode, this string is used to select the correct physics init/run/finalize calls …

ccpp_prebuild version of multi-suite static build, cleanup validation of SDF used

---

scripts/metadata_parser.py

The Fortran 2003 standard defines a `select type` construct, where the individual cases are selected using
```
select type (my_type)
type is (XYZ)
type is(ABC)
end select
```
If such a `select type` statement occurs inside a variable definition file (i.e. a file that is parsed by `ccpp_prebuild.py` for host model variable definitions, then this leads to an error. The workaround proposed here skips line where the first (and not last) word is `type`, and the second word is either `is` or starts with `is(`.
This has been tested by compiling the NEMSfv3gs code manually on MacOSX/GNU and Theia/Intel with such a variable definition file included.
Reference for `select type` statement: https://www.ibm.com/support/knowledgecenter/en/SSGH4D_16.1.0/com.ibm.xlf161.aix.doc/language_ref/typecon.html …

ccpp-prebuild metadata parser: workaround to skip 'type is' statements

---

scripts/ccpp_prebuild.py
scripts/common.py
scripts/mkstatic.py

This PR adds a clean option `--clean` to ccpp_prebuild.py which removes all files created by the same command without `--clean` and then exits.
See https://github.com/NCAR/NEMSfv3gfs/pull/158 for a description of related changes and testing.

Add clean option to ccpp_prebuild.py

---

doc/DevelopersGuide/host_cap_template.F90

Updated the host_cap_template.F90 file used for documentation to use the static build only:
- used ccpp_static_api for ccpp_physics_{init,run,finalize}
- passed ccpp_suite_name into the subroutines that need it
- removed scheme optional argument in the physics_run subroutine

Update host_cap_template.F90 for documentation

---

scripts/fortran_tools/parse_fortran.py
scripts/parse_tools/parse_checkers.py

Fix parsing of the initial type definition line in Ftype_type_decl.
Note, this is an updated file from the new_metadata_parser branch so other code has changed as well (but I do not think it is used in gmtb/develop).

Allow comments in type definition lines

---

scripts/convert_metadata.py
scripts/convert_metadata_schemes_using_typedef_dims.py
scripts/metadata2html.py
scripts/metadata_table.py
scripts/metavar.py

https://github.com/NCAR/NEMSfv3gfs/pull/212
https://github.com/NCAR/ccpp-physics/pull/293
https://github.com/NCAR/FV3/pull/184
https://github.com/NCAR/ccpp-framework/pull/208
https://github.com/NCAR/NEMS/pull/1
For regression testing, see https://github.com/NCAR/NEMSfv3gfs/pull/212.
Changes in ccpp-framework:
- first version of metadata to html converter, making use of the existing `metadata_header` class and extending it with a `to_html` class function
- `scripts/convert_metadata*.py`: skip adding `\htmlinclude` statements for blank metadata tables

First version of metadata2html converter

---

scripts/mkcap.py

add the variable standard name and container to the exception message generated by a unit conversion failure for user-friendliness

Unit conversion error verbosity

---

scripts/common.py
scripts/conversion_tools/unit_conversion.py
scripts/convert_metadata_schemes_using_typedef_dims.py
scripts/metadata_parser.py
src/ccpp_types.F90
src/ccpp_types.meta

- convert `src/ccpp_types.F90` to new metadata format (`scripts/common.py`: register missing CCPP internal variables)
- `scripts/conversion_tools/unit_conversion.py`: register unit conversion from micrometer to meter and vice versa
- `scripts/convert_metadata_schemes_using_typedef_dims.py`: add missing variables to GFS_typedefs-based dimensions dictionary that are not used by FV3
- `scripts/metadata_parser.py`: warn or raise exception (currently warn) if old metadata is found

Convert all schemes to new metadata, new unit conversion micrometer<->meter, merge gsd/develop

---

doc/CCPPtechnical/source/ScientificDocRules.inc
scripts/ccpp_prebuild.py
scripts/common.py
scripts/metadata2html.py

This PR adds a batch processing option to the Python script `metadata2html.py`, which reads the host model's CCPP prebuild configuration and attempts to convert `.meta` files for each of the schemes and variable definition files defined.
For backward compatibility with the old metadata format, a warning is issued (instead of an exception) if the `.meta` cannot be found for a given file.
The technical documentation is updated to reflect these changes.
This PR requires adding a new variable to the CCPP prebuild config, see PR https://github.com/NCAR/NEMSfv3gfs/pull/246. A similar PR for SCM will be created in the next days when all SCM metadata is converted to the new format.

gmtb/develop: metadata2html batch processing

---

doc/CCPPtechnical/source/BuildingRunningHostModels.rst

Remove documentation for TRANSITION mode from tech doc.
This change is tested together with https://github.com/NCAR/NEMSfv3gfs/pull/251 and other PRs listed below.

gmtb/develop: remove TRANSITION mode

---

test/unit_tests/README.md
test/unit_tests/sample_files/double_header.meta
test/unit_tests/sample_files/test_bad_dimension.meta
test/unit_tests/sample_files/test_bad_type_name.meta
test/unit_tests/sample_files/test_duplicate_variable.meta
test/unit_tests/sample_files/test_host.meta
test/unit_tests/sample_files/test_invalid_intent.meta
test/unit_tests/sample_files/test_missing_intent.meta
test/unit_tests/sample_files/test_multi_ccpp_arg_tables.meta
test/unit_tests/test_metadata_table.py

This is the first commit of unit testing for capgen.  There are 8 tests so far:
1) a good host file
2) a bad dimension
3) a bad type name
4) duplicate header in meta file
5) duplicate variable
6) a good host file with 4 occurrences of ccpp-arg-table
7) a bad intent
8) a missing intent
Tests 1-7 pass, test 8 fails.  An issue has been submitted.

Feature/capgen Add unit test for capgen parse_metadata_file

---

scripts/ccpp_prebuild.py
scripts/common.py
scripts/metadata2html.py
scripts/metavar.py
scripts/mkcap.py
scripts/mkdoc.py
scripts/mkstatic.py
scripts/parse_tools/parse_checkers.py

https://github.com/NCAR/ccpp-framework/pull/230
https://github.com/NCAR/ccpp-physics/pull/340
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/5
https://github.com/NOAA-EMC/fv3atm/pull/1
https://github.com/ufs-community/ufs-weather-model/pull/1
https://github.com/NOAA-EMC/NEMS/pull/11 (merged)
https://github.com/NOAA-EMC/NEMS/pull/12
See https://github.com/ufs-community/ufs-weather-model/pull/1 for a description and regression testing information.
This PR for ccpp-framework merges the previously approved changes made for the gmtb/develop branch into the master branch.
Changes specific to ccpp-framework:
- cleanup of prebuild scripts (move common code into common.py module, ...)
- add capability to create html pages from metadata files for all schemes in a CCPP …

Update master from gmtb/develop 2019/10/16

---

scripts/ccpp_prebuild.py
scripts/mkcap.py
scripts/mkdoc.py
scripts/mkstatic.py

Modifications of ccpp_prebuild.py to support out-of-source builds for static CCPP builds, required for parallel cmake builds in NEMSfv3gfs.
Backward compatible for in-source builds for both static and dynamic builds.

ccpp_prebuild: out-of-source builds for parallel cmake builds (target master)

---

schemes/check/ccpp_prebuild_config.py

Second bugfix for travis: add missing entry to schemes/check/ccpp_prebuild_config.py following https://github.com/NCAR/ccpp-framework/pull/235 and https://github.com/NCAR/ccpp-framework/pull/230. Merge immediately, no effect on any model.

Bugfix #2 for travis test in schemes/check/ccpp_prebuild_config.py

---

scripts/ccpp_prebuild.py
scripts/metadata2html.py

This PR updates the logic around the current command line arguments `--builddir` (for `ccpp_prebuild.py`) and `--basedir` (for `metadata2html.py`).
- for `ccpp_prebuild.py`: use default value from the CCPP prebuild config (newly added) if not provided on the command line; this means that the default build is in-source, but by specifying `--builddir` an out-of-source build can be requested; this is also backward compatible with the current settings in UFS and SCM
- for `metadata2html.py`: since it does not make sense to create the html tables from the CCPP metadata outside of the source directories (all accompanying doxygen files are in-source), always use the default value from the CCPP prebuild config, remove the command line argument entirely
With this change, it is possible to run …

dtc/develop: update logic around builddir (ccpp_prebuild.py) / basedir (metadata2html.py)

---

src/CMakeLists.txt
src/ccpp.F90
src/ccpp_api.F90

This PR removes code required for the dynamic CCPP option only from the static build.
@DusanJovic-NOAA, for your information, this means that the offending warning messages when compiling ccpp-framework with the GNU compiler are gone.
Associated PRs see below, for regression testing see NCAR/ufs-weather-model#9.

dtc/develop: compile only required source files in static mode

---

scripts/ccpp_prebuild.py
scripts/metadata2html.py
scripts/mkcap.py
scripts/mkstatic.py
src/CMakeLists.txt
src/ccpp.F90
src/ccpp_api.F90

This PR contains:
- bugfix #2 for travis test in schemes/check/ccpp_prebuild_config.py
- optimization/cleanup: only compile the files that are needed when static build is selected
- improved handling of builddir/basedir argument to ccpp_prebuild.py and metadata2html.py
- improved error handling and diagnostic output for ccpp_prebuild.py

ufs_public_release: updates from DTC (bugfixes, cleanup, optimization)

---

scripts/ccpp_prebuild.py
scripts/metadata2html.py
scripts/mkcap.py
scripts/mkstatic.py
src/CMakeLists.txt
src/ccpp.F90
src/ccpp_api.F90

This PR contains:
- bugfix #2 for travis test in schemes/check/ccpp_prebuild_config.py
- optimization/cleanup: only compile the files that are needed when static build is selected
- improved handling of builddir/basedir argument to ccpp_prebuild.py and metadata2html.py
- improved error handling and diagnostic output for ccpp_prebuild.py
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/11
https://github.com/NCAR/ccpp-framework/pull/246
https://github.com/NCAR/ccpp-physics/pull/372
https://github.com/NOAA-EMC/fv3atm/pull/30
https://github.com/ufs-community/ufs-weather-model/pull/18
For regression testing, see https://github.com/ufs-community/ufs-weather-model/pull/18.

master update from dtc/develop 2019/12/17

---

CMakeLists.txt
schemes/check/ccpp_prebuild_config.py
src/CMakeLists.txt

Fix travis build/testing by setting STATIC option correctly for standalone build and adding the missing new configuration option DEFAULT_BUILD_DIR to the standalone build CCPP prebuild config.

master: fix travis build

---

src/CMakeLists.txt

Remove reference to libxml2, this not required for the static build. Avoids that users need to install libxml2 on their systems for something that doesn't get used at all.
https://github.com/NCAR/ccpp-framework/pull/261
https://github.com/NOAA-EMC/fv3atm/pull/55
https://github.com/ufs-community/ufs-weather-model/pull/46
For regression testing, see https://github.com/ufs-community/ufs-weather-model/pull/46.

release/public-v4: remove reference to libxml2

---

scripts/metadata_parser.py
scripts/mkcap.py

This PR contains the following PRs:
#252, correct log message for automated unit conversions
#254, bugfix for converting optional attribute from new metadata for ccpp_prebuild.py.
https://github.com/NCAR/ccpp-framework/pull/260
https://github.com/NCAR/ccpp-physics/pull/394
https://github.com/NCAR/fv3atm/pull/25
https://github.com/NCAR/ufs-weather-model/pull/21
See https://github.com/NCAR/ufs-weather-model/pull/21 for regression testing information.

dtc/develop: combined PR with bugfixes for ccpp_prebuild.py

---

scripts/metadata_parser.py

scripts/metadata_parser.py: bugfix for converting optional attribute from new to old metadata

dtc/develop: bugfix for converting optional attribute from new metadata for ccpp_prebuild.py

---

scripts/mkcap.py

`scripts/mkcap.py`: change the log message to match the logic for automated unit conversions in `ccpp_prebuild.py`.
`ccpp_prebuild.py`:
```
...
if var.intent=='inout':
var.convert_from(metadata_define[var_name][0].units)
var.convert_to(metadata_define[var_name][0].units)
elif var.intent=='in':
var.convert_from(metadata_define[var_name][0].units)
elif var.intent=='out':
var.convert_to(metadata_define[var_name][0].units)
...
```
This means that `convert_to` should say "after returning from" and `convert_from` should say "before entering" (and not vice versa).
This can be merged anytime.

dtc/develop: correct log message for automated unit conversions

---

scripts/metadata_parser.py
scripts/mkcap.py

See https://github.com/ufs-community/ufs-weather-model/pull/84 for a description of the changes.
https://github.com/NOAA-EMC/NEMS/pull/43
https://github.com/NCAR/ccpp-physics/pull/410
https://github.com/NCAR/ccpp-framework/pull/268
https://github.com/NOAA-EMC/fv3atm/pull/81
https://github.com/ufs-community/ufs-weather-model/pull/84
See https://github.com/ufs-community/ufs-weather-model/pull/84 for regression testing information.

Update master from dtc/develop 2020/03/17

---

CMakeLists.txt

set a value for cmake policy 0077 in order to not reset the STATIC variable within CMakeLists.txt when building with the SCM
needed for https://github.com/NCAR/gmtb-scm/pull/176

CMake Policy 0077

---

scripts/ccpp_prebuild.py
scripts/common.py
scripts/conversion_tools/__init__.py
scripts/metadata_parser.py
scripts/metadata_table.py
scripts/mkdoc.py
scripts/mkstatic.py
scripts/parse_tools/__init__.py
scripts/parse_tools/parse_checkers.py
scripts/parse_tools/parse_object.py

This PR updates the CCPP prebuild scripts (`ccpp_prebuild.py` and dependencies) so that they are compatible with both Python 2.7 and Python 3 (tested with Python 3.7).
Credits for this PR go to Nick Weber (@njweber2) for sending these changes in an email.
`ccpp_prebuild.py` tested manually (in addition to the regression testing):
```
./FV3/ccpp/framework/scripts/ccpp_prebuild.py --config=FV3/ccpp/config/ccpp_prebuild_config.py
./FV3/ccpp/framework/scripts/ccpp_prebuild.py --config=FV3/ccpp/config/ccpp_prebuild_config.py --debug
./FV3/ccpp/framework/scripts/ccpp_prebuild.py --config=FV3/ccpp/config/ccpp_prebuild_config.py --static --suites=FV3_GFS_v16beta,FV3_GFS_v15p2_no_nsst
./FV3/ccpp/framework/scripts/ccpp_prebuild.py --config=FV3/ccpp/config/ccpp_prebuild_config.py --static …
```

release/public-v4: Python 3 compatibility for CCPP prebuild scripts

---

scripts/ccpp_prebuild.py
scripts/common.py
scripts/conversion_tools/__init__.py
scripts/metadata_parser.py
scripts/metadata_table.py
scripts/mkcap.py
scripts/mkdoc.py
scripts/mkstatic.py
scripts/parse_tools/__init__.py
scripts/parse_tools/parse_checkers.py
scripts/parse_tools/parse_object.py

This PR is required for merging RRTMGP into CCPP. It updates/extends the CCPP prebuild script to provide information on CCPP kind and type definitions to the host model.
This is required so that the host model build system (calling/using the ccpp-physics cmake build system) can install and find the Fortran modules containing the definitions of the RRTMGP-internal DDTs, and also the already existing DDTs such as those in `GFS_typedefs.F90`. This is an important cleanup, because it means we do not have to manually list and compile the type definitions on the host model side (in addition to being compiled and installed by CCPP).
The PR also includes an update of the NCAR dtc/develop branch from the NCAR master branch, as well as an update of the CCPP prebuild scripts to work with Python 3 as …

RRTMGP in CCPP (updates to ccpp_prebuild.py)

---

scripts/ccpp_prebuild.py
scripts/mkstatic.py

Changes in ccpp-framework:
- `scripts/mkstatic.py`: avoid recreating the auto-generated caps and API when no changes are made
https://github.com/NCAR/ccpp-framework/pull/277
https://github.com/NCAR/ccpp-physics/pull/425
https://github.com/NCAR/fv3atm/pull/35
https://github.com/NCAR/ufs-weather-model/pull/33
For regression testing information, see https://github.com/NCAR/ufs-weather-model/pull/33.

dtc/develop: speed up static compilation

---

CMakeLists.txt
scripts/conversion_tools/unit_conversion.py

This PR contains:
- add cm-to-m conversion and reverse for HWRF Noah LSM (from @grantfirl)
- update `CMakeLists.txt`: require CMake 3.0, remove legacy syntax for policy CMP0048
https://github.com/NCAR/GFDL_atmos_cubed_sphere/pull/11
https://github.com/NCAR/ccpp-framework/pull/281
https://github.com/NCAR/ccpp-physics/pull/432 (contains https://github.com/NCAR/ccpp-physics/pull/424)
https://github.com/NCAR/fv3atm/pull/40
https://github.com/NCAR/ufs-weather-model/pull/38/files
For regression testing information, see https://github.com/NCAR/ufs-weather-model/pull/38/files.

dtc/develop: add unit conversions for Noah LSM, update CMakeLists.txt

---

scripts/ccpp_prebuild.py
scripts/common.py
scripts/metadata_parser.py

This PR:
- fix Python 3 decoding error in `scripts/common.py`
- raise proper exceptions when decoding non-ascii files in `scripts/metadata_parser.py`
- parse all suite definition files if suites argument is not present when calling `ccpp_prebuild.py`; this addresses issue https://github.com/NCAR/ccpp-framework/issues/293
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/20
https://github.com/NCAR/ccpp-framework/pull/292
https://github.com/NCAR/ccpp-physics/pull/451
https://github.com/NOAA-EMC/fv3atm/pull/115
https://github.com/NOAA-EMC/NEMS/pull/62
https://github.com/ufs-community/ufs-weather-model/pull/126
For regression testing information, see https://github.com/ufs-community/ufs-weather-model/pull/126.

Fix/report Python3 decoding errors, parse all suites if --suites=... argument not present

---

scripts/common.py

This PR:
- scripts/common.py: fix decoding errors detected on Stampede
https://github.com/NCAR/ccpp-framework/pull/295
https://github.com/NOAA-EMC/fv3atm/pull/117
https://github.com/NOAA-EMC/NEMS/pull/63
https://github.com/ufs-community/ufs-weather-model/pull/139
For regression testing information, see below https://github.com/ufs-community/ufs-weather-model/pull/139.

Fix decoding errors in scripts/common.py's execute_cmd

---

test/unit_tests/sample_scheme_files/reorder.F90
test/unit_tests/sample_scheme_files/reorder.meta
test/unit_tests/sample_scheme_files/temp_adjust.F90
test/unit_tests/sample_scheme_files/temp_adjust.meta
test/unit_tests/test_metadata_scheme_file.py

Two tests are:
- Test that metadata file matches Fortran when routines are in the same order
- Test that metadata file matches Fortran when order of routines differ
All tests pass.

Feature/capgen Initial commit of unit testing for capgen parse_scheme_files function

---

scripts/common.py

This PR contains additional bugfixes for Python 3 (from master). Without these, using Python 3 users on certain machines (including Stampede) will see an Exception from `ccpp_prebuild.py` and the build is broken.
https://github.com/NCAR/ccpp-framework/pull/303
https://github.com/NOAA-EMC/fv3atm/pull/130
https://github.com/ufs-community/ufs-weather-model/pull/149
For regression testing information, see below https://github.com/ufs-community/ufs-weather-model/pull/149.

release/public-v4: additional python3 bug fixes

---

scripts/ccpp_prebuild.py
scripts/conversion_tools/unit_conversion.py
scripts/metadata2html.py
scripts/mkcap.py

This PR contains the following changes:
- `scripts/conversion_tools/unit_conversion.py`: add conversion from degrees to radians and vice versa, address issue #309 
-  `scripts/ccpp_prebuild.py`, `scripts/mkcap.py`: address issue #309 (use correct Python syntax to test if a variable is a list or a dictionary)
- a bugfix from @mzhangw for `metadata2html.py` (https://github.com/NCAR/ccpp-framework/pull/312)

Add unit conversion from degrees to radians, address isssue #309

---

test/unit_tests/sample_scheme_files/preproc_defs_test1.F90
test/unit_tests/sample_scheme_files/preproc_defs_test1.meta
test/unit_tests/sample_scheme_files/preproc_defs_test2.F90
test/unit_tests/sample_scheme_files/preproc_defs_test2.meta
test/unit_tests/test_metadata_scheme_file.py

- Add test for correct detection of a variable that remains in the subroutine argument
list due to an undefined pre-processor directive, but IS NOT present in the meta file
- Add test for correct detection of a variable that is removed from the subroutine
argugment list due to a pre-processor directive, but IS present in the meta file
- Add corresponding fortran and metadata files for tests
Your code has been rated at 10.00/10
All tests pass.

Add two unit tests for metadata scheme to test preprocessor directives

---

scripts/ccpp_prebuild.py
scripts/common.py
scripts/metadata_parser.py
scripts/metadata_table.py
scripts/metavar.py
scripts/mkstatic.py
src/ccpp_types.meta

This PR fixes https://github.com/NCAR/ccpp-framework/issues/308 for `ccpp_prebuild.py`.
Changes:
- add capability to parse new, required sections starting with `[ccpp-table-properties]`
- the names in the `name = ...` attributes for these sections cannot end with one of the predefined CCPP stages (e.g. `_init`)
- the type for these sections must be the same table as the corresponding `[ccpp-arg-table]` sections
- remove unnecessary duplication of information in `ccpp_prebuild.py`'s `argument` dictionary: instead of `arguments[module_name][scheme_name][subroutine_name]`, use `arguments[scheme_name][subroutine_name]`; this is sufficient, because per requirement `module_name = scheme_name`
- fix a bug in `src/ccpp_types.meta`
- fix a warning in `scripts/metavar.py` by changing `is` to `==`: …

Add dependencies to metadata

---

scripts/ccpp_prebuild.py

This PR fixes a bug that shows up with Python 3 only, for which dict.values() does not automatically return a list (unlike in Python 2).
For (regression) testing information, see https://github.com/ufs-community/ufs-weather-model/pull/201.
https://github.com/NCAR/ccpp-framework/pull/322
https://github.com/NOAA-EMC/fv3atm/pull/171
https://github.com/ufs-community/ufs-weather-model/pull/201

scripts/ccpp_prebuild.py: bugfix for Python 3

---

scripts/metadata_parser.py

As the title says.
https://github.com/NCAR/ccpp-framework/pull/326
https://github.com/NCAR/ccpp-physics/pull/504
https://github.com/NCAR/fv3atm/pull/63
https://github.com/NCAR/ufs-weather-model/pull/64
For regression testing information, see https://github.com/NCAR/ufs-weather-model/pull/64.

feature/transition-to-capgen-1: remove obsolete warning message from scripts/metadata_parser.py

---

test/unit_tests/sample_scheme_files/CCPPeq1_var_in_fort_meta.F90
test/unit_tests/sample_scheme_files/CCPPeq1_var_in_fort_meta.meta
test/unit_tests/sample_scheme_files/CCPPeq1_var_missing_in_fort.F90
test/unit_tests/sample_scheme_files/CCPPeq1_var_missing_in_fort.meta
test/unit_tests/sample_scheme_files/CCPPeq1_var_missing_in_meta.F90
test/unit_tests/sample_scheme_files/CCPPeq1_var_missing_in_meta.meta
test/unit_tests/sample_scheme_files/CCPPgt1_var_in_fort_meta.F90
test/unit_tests/sample_scheme_files/CCPPgt1_var_in_fort_meta.meta
test/unit_tests/sample_scheme_files/CCPPnotset_var_missing_in_meta.F90
test/unit_tests/sample_scheme_files/CCPPnotset_var_missing_in_meta.meta
test/unit_tests/sample_scheme_files/invalid_dummy_arg.meta
test/unit_tests/sample_scheme_files/invalid_subr_stmnt.meta
test/unit_tests/sample_scheme_files/mismatch_intent.meta
test/unit_tests/sample_scheme_files/missing_arg_table.meta
test/unit_tests/sample_scheme_files/missing_fort_header.meta
test/unit_tests/sample_scheme_files/reorder.meta
test/unit_tests/sample_scheme_files/temp_adjust.meta
test/unit_tests/test_metadata_scheme_file.py

- Update unit tests to include ccpp-table-properites
- Rename sample files preproc_defs_test*.meta to be more descriptive
- Rename sample files preproc_defs_test*.F90 to be more descriptive
pylint rated at 10.00/10 for test_metadata_scheme_file.py
All tests pass for test_metadata_scheme_file.py
Still need to update test_metadata_table.py

Updates to unit tests in test_metadata_scheme_file.py:

---

scripts/ccpp_prebuild.py

Add additional information to CCPP prebuild log when/before performing unit conversions.
https://github.com/NCAR/ccpp-physics/pull/506
https://github.com/NCAR/ccpp-framework/pull/327
https://github.com/NCAR/fv3atm/pull/64
https://github.com/NCAR/ufs-weather-model/pull/65
For regression testing information, see https://github.com/NCAR/ufs-weather-model/pull/65.

feature/transition-to-capgen-1: improve logging output for unit conversions

---

scripts/ccpp_prebuild.py
scripts/metadata_parser.py

This PR updates master with the combined changes in NCAR's feature/transition-to-capgen-1 branch. The changes are tiny and are not strictly required for the transition, but provide better information in the log files produced by `ccpp_prebuild.py`
https://github.com/NCAR/ccpp-physics/pull/508
https://github.com/NCAR/ccpp-framework/pull/330
https://github.com/NOAA-EMC/fv3atm/pull/186
https://github.com/ufs-community/ufs-weather-model/pull/216
For regression testing information, see https://github.com/ufs-community/ufs-weather-model/pull/216

Merge NCAR feature/transition-to-capgen-1 (prepare for cap_gen.py, step 1) to master

---

scripts/ccpp_prebuild.py

As the title says. Sorting the schemes avoids unnecessary recompiling.
The problem of a different order in the auto-generated cmake/gnumake/shell snippets that contain the list of schemes and dependencies to compile doesn't happen on my Mac, but on hera for example.
This PR will be combined with other PRs for the UFS weather model in the near future, but please review and approve when you get the chance.

scripts/ccpp_prebuild.py: sort schemes before creating makefile snippets to avoid recompiling

---

scripts/ccpp_capgen.py
scripts/file_utils.py

Build behavior updates for capgen.
Fixes #278 
Fixes #293

Build updates for unification

---

scripts/ccpp_prebuild.py

This is one line fix in ccp_prebuild.py that fixes https://github.com/NCAR/ccpp-framework/issues/342

bug fix in ccpp_prebuild error checking

---

scripts/ccpp_prebuild.py
scripts/common.py
scripts/metadata_parser.py
scripts/mkstatic.py

This PR contains the following changes:
- Implementation of CCPP `timestep_init` and `timestep_final` phases
- Use CCPP_stages dictionary to abbreviate `timestep_init` and `timestep_final` as `tsinit` and `tsfinal` in cap subroutine names
- Drop requirement that CCPP schemes have to have subroutines for each phase, even if those are empty and don't have CCPP metadata tables
https://github.com/ufs-community/ufs-weather-model/pull/337
https://github.com/NOAA-EMC/fv3atm/pull/217
https://github.com/NCAR/ccpp-physics/pull/534
https://github.com/NCAR/ccpp-framework/pull/344
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/47
For regression testing information, see https://github.com/ufs-community/ufs-weather-model/pull/337.

Implementation of CCPP timestep_init and timestep_final phases

---

scripts/mkstatic.py

Because physics schemes do not know the size of each dimension of a variable allocated by the host model, we need to always copy data in when data is converted from blocked data structures into contiguous arrays.
A discussion of the meaning of `intent(out)` for a physics scheme will be held at the ccpp-framework developer meeting on 04/27/2021.
https://github.com/NCAR/ccpp-framework/pull/368
https://github.com/NCAR/ccpp-physics/pull/641
https://github.com/NOAA-EMC/fv3atm/pull/291
https://github.com/ufs-community/ufs-weather-model/pull/541
For regression testing, see https://github.com/ufs-community/ufs-weather-model/pull/541

scripts/mkstatic.py: always copy data in, independent of the intent

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Addresses issue #367 
https://github.com/NCAR/ccpp-framework/pull/372
https://github.com/NCAR/ccpp-physics/pull/658
https://github.com/NOAA-EMC/fv3atm/pull/300
https://github.com/ufs-community/ufs-weather-model/pull/572
For regression testing, see https://github.com/ufs-community/ufs-weather-model/pull/572

Add pull request and issue templates

---

scripts/metadata_parser.py

This PR removes an overly restrictive and unnecessary test of doxygen comments when looking for scheme tables from scripts/metadata_parser.py.
https://github.com/NCAR/ccpp-physics/pull/627
https://github.com/NCAR/ccpp-framework/pull/366
https://github.com/NOAA-EMC/fv3atm/pull/285
https://github.com/ufs-community/ufs-weather-model/pull/529
For regression testing, see https://github.com/ufs-community/ufs-weather-model/pull/529

Remove overly restrictive testing of doxygen comments when looking for scheme tables from scripts/metadata_parser.py

---

scripts/ccpp_suite.py
scripts/ddt_library.py
scripts/fortran_tools/__init__.py
scripts/metadata_table.py
scripts/metavar.py
scripts/parse_tools/__init__.py
scripts/parse_tools/parse_checkers.py
scripts/parse_tools/parse_object.py
test/advection_test/test_host.F90
test/advection_test/test_host_mod.meta
test/capgen_test/make_ddt.meta
test/capgen_test/test_host.F90
test/capgen_test/test_host_mod.meta
test/unit_tests/sample_files/test_multi_ccpp_arg_tables.meta
test/unit_tests/sample_files/test_unknown_ddt_type.meta
test/unit_tests/test_metadata_table.py

Also, added infrastructure and a method to find the intrinsic elements of a compound array or DDT
closes #377

Changed ddt_type metadata keyword to just type.

---

scripts/metadata_table.py
scripts/metavar.py

This PR brings updates that were made in main (master) to feature/capgen, which should have happened much earlier. The idea is to simplifiy PR https://github.com/NCAR/ccpp-framework/pull/391 and the follow-up merge back from main to feature/capgen. The burden of resolving merge conflicts will be on me when feature/capgen updates from this PR get pulled into https://github.com/NCAR/ccpp-framework/pull/391.
Changes:
- update example metadata table in `metadata_table.py` to include `dependencies` and `relative_path`, adjust indents
- add active attribute to `metavar.py`'s variable class
- update the `true/false` logic as discussed last year to avoid code duplication
These changes have been tested, reviewed, and approved previously in various PRs (#205, #307, #317).

Add active attribute and update true/false logic in metavar.py, update example metadata table in metadata_table.py

---

scripts/ccpp_prebuild.py
scripts/metadata_parser.py
scripts/metavar.py
scripts/mkcap.py
scripts/mkstatic.py
scripts/parse_tools/parse_checkers.py

1. Remove support for optional arguments from `capgen`'s metadata parser. The code now raises an Exception when it finds an `optional` attribute. Note that the `capgen` metadata parser is used by `ccpp_prebuild`.
2. Remove support for optional arguments from `ccpp_prebuild` and all its helper scripts.
3. Fix two failing doctests in `metavar.py` and `parse_checkers.py`.
After this PR, the feature/capgen branch must be updated from main.
Yes. Need to remove all optional attributes from the metadata.
Note also that the `OPTIONAL_ARGUMENTS` section in the CCPP prebuild config is ignored.
Fixes #407
https://github.com/NCAR/ccpp-framework/pull/408
https://github.com/earth-system-radiation/rte-rrtmgp/pull/143
https://github.com/NCAR/ccpp-physics/pull/766 …

Remove optional arguments from CCPP (capgen metadata parser and ccpp_prebuild scripts)

---

CMakeLists.txt
scripts/ccpp_prebuild.py
scripts/metadata_parser.py
scripts/metavar.py
scripts/mkcap.py
scripts/mkstatic.py
scripts/parse_tools/parse_checkers.py
src/CMakeLists.txt

Merge main into feature capgen 2021/11/05
Updates include:
- remove support for optional arguments in `ccpp_prebuild` scripts
- add debugging features to `ccpp_prebuild` scripts
- update the `ccpp_prebuild` cmake build
- resolve conflicts from merge, a tiny change for one doctest in `metavar.py`, update call to parse_metadata_file in prebuild's `metadata_parser.py`
All changes except commits 0159166bd4a1b670ed94ab5a06018ca500b4eb1d and ee22e68deeb745228071cf511bdb56a662bb46a4 have been reviewed and approved before they were merged into main.
Testing:
- `test/run_test.sh` passes
- `PYTHONPATH=$PWD/scripts:$PWD/scripts/parse_tools pytest` passes
- latest ufs-weather-model code compiles when making several bugfixes for invalid units in fv3atm and ccpp-physics …

Merge main into feature capgen 2021/11/05

---

scripts/fortran_tools/parse_fortran_file.py
test/capgen_test/temp_calc_adjust.F90

Fixes https://github.com/NCAR/ccpp-framework/issues/359 (https://github.com/NCAR/ccpp-framework/issues/359).
The `capgen` Fortran parser is updated to know whether it is inside a `contains` section of a CCPP scheme. If so, the contents is ignored until an `end subroutine scheme_name_ccpp_phase` (e.g. `end subroutine mp_thompson_run`) is found.
Note that this fix requires that `end subroutine` statements are labeled with the subroutine name, i.e. `subroutine mp_thompson_run` requires the end statement to be `end subroutine mp_thompson_run` and not just `end_subroutine`). This has been a soft requirement for `ccpp_prebuild.py`, which warns users that an unlabeled `end subroutine` statement was found, but in must cases was able to proceed.
A more complicated solution that does not require …

Fix capgen Fortran parser to recognize nested subroutines/functions

---

test/advection_test/cld_ice.F90
test/advection_test/cld_ice.meta

Add system test for doxygen comments between metadata hooks and CCPP entry point (subroutine) to make sure various doxygen comments and blank lines are parsed correctly/ignored between CCPP metadata hooks and the Fortran subroutines.
Issue https://github.com/NCAR/ccpp-framework/issues/369 reports that certain doxygen comments between the metadata hooks and the subroutines are "not parsed correctly" (i.e. are  not ignored). I was going to fix this problem and found that the current `capgen` metadata parser can handle those cases just fine. I added a CCPP entry point to cover these tests.
"Fixes https://github.com/NCAR/ccpp-framework/issues/369"
Testing:
test removed: None
unit tests: None
system tests: Add one system test to cover blank lines and doxygen …

Add system test for doxygen comments between metadata hooks and CCPP entry point (subroutine)

---

scripts/ccpp_prebuild.py
scripts/mkdoc.py

This PR fixes https://github.com/NCAR/ccpp-framework/issues/437, see description there, and provides an additional comment for one subroutine in `ccpp_prebuild.py`
Fixes: #437 
Testing:
- `metadata2html.py` works for in-source and out-of-source builds
- ufs-weather-model compiles and runs and gives b4b identical results

Fix metadata2html.py, add some more documentation to ccpp_prebuild.py

---

CMakeLists.txt

Update `CMakeLists.txt` to:
- remove the custom build mode "BitForBit", also known as REPRO mode, and previously needed for the UFS
- update list of authors
Related ufs-weather-model issue: https://github.com/ufs-community/ufs-weather-model/issues/1161
Testing:
test removed: none 
unit tests: pass
system tests: pass
manual testing: ufs-weather-model regression testing, see https://github.com/ufs-community/ufs-weather-model/pull/1171
https://github.com/NCAR/ccpp-physics/pull/909
https://github.com/NOAA-EMC/fv3atm/pull/524
https://github.com/ufs-community/ufs-weather-model/pull/1171

Remove custom "BitForBit" (aka REPRO) mode

---

scripts/ccpp_track_variables.py
scripts/mkstatic.py

This PR changes the output slightly, so that the ordered lists of schemes are now broken down by group. This is done because different groups in a physics suite can be called in different orders depending on the logic of the host model, so only within each group is a set of schemes guaranteed to be called in that order.
This PR also fixes a bug in ccpp_track_variables.py that double-counted variables in schemes that have .meta files containing descriptions of more than one scheme.
Finally, this PR has some small improvements suggested by pylint, including removing trailing whitespace and trimming long lines.
Cases with partial matches or no matches found will not be affected by this change.
Fixes: #450 (duplicate counting of schemes)
Testing:
Ran script against …

Bug fix and improvement for ccpp_track_variables tool

---

README.md

Two links in the README.md point to v5 versions of documentation. This PR will update those links for version 6. Note that these links are currently broken as those links have not yet been populated.

Update README links for v6

---

scripts/mkstatic.py

Per discussion on #337, this implements a hard cap on suite names of 37 characters for ccpp_prebuild.
User interface changes?: [ Yes ]
If a user attempts to run ccpp_prebuild with a suite name longer than 37 characters, prebuild will fail with an error message indicating the problem.
Fixes: Part of #337 (ccpp_prebuild only)
Testing:
test removed:
unit tests:
system tests:
manual testing: Ran ccpp_prebuild.py both stand-alone and for SCM, script ran successfully for existing suites, and failed as expected when a new long suite name was introduced. Will run more tests if requested.

Limit suite names to 37 characters or less

---

scripts/ccpp_state_machine.py
scripts/state_machine.py

Fix Python 3.11 errors as described in https://github.com/NCAR/ccpp-framework/issues/457
With these changes, the error from
```
cd tests
PYTHONPATH=$PWD/../scripts/parse_tools:$PWD/../scripts:$PYTHONPATH python3.11 test_metadata_parser.py
```
is fixed. I asked @DusanJovic-NOAA to test this branch with the ufs-weather-model on his Fedora 37 machine, which uses Python 3.11 as default, and I would like to ask @mkavulich @grantfirl @dustinswales to test this branch with their versions of Python in the CCPP-SCM, please.
As noted in https://github.com/NCAR/ccpp-framework/issues/457, I cannot run the unit tests in ccpp-framework that require `pytest`. I ran the following unit tests successfully with Python 3.11:
```
cd tests
PYTHONPATH=$PWD/../scripts/parse_tools:$PWD/../scripts:$PYTHONPATH …
```

Fix ccpp-framework errors with Python 3.11

---

scripts/common.py
test/unit_tests/test_common.py

As described in #458, there is a problem with the unit converter if
attempting to convert from unit "1" to any other value: while this
should result in an error (units of "1" can't be converted to anything 
else), the error that results is not descriptive (due to "1" not being a
valid python function name). This change adds an if statement to
correctly pass "1" as a valid unit so that the correct error message 
is printed.
Fixes: #458 Unit converter does not handle units = 1 correctly for incompatible conversions
Testing:
test removed: None
unit tests: All existing passed. Added new unit test for validating the string_to_python_identifier() function for both valid and invalid inputs
system tests: None
manual testing: Ran ccpp_prebuild with SCM with a modified …

Fix error message for unit conversions involving unit "1"

---

test/unit_tests/test_common.py
test/unit_tests/test_var_transforms.py

This PR is a demo to begin adding more unit test coverage to the CCPP-framework. Since a unit test was recently added for the `test_string_to_python_identifier` function in `common.py`, I added unit tests for the remaining functions in that file.
To run these unit tests, simply navigate to the `test/unit_tests` directory and run the script (with Python 3.7 or higher):
```
python test_common.py 
.....
----------------------------------------------------------------------
Ran 5 tests in 0.023s
OK
```
Fixes: No issue specific to this change. This test focuses on the `ccpp_prebuild` portion of code, but should be a stepping stone to a number of issues relating to `capgen` unit tests.
Testing:
unit tests: All passed

Add more unit tests for routines in common.py

---

scripts/common.py
scripts/mkstatic.py
src/ccpp_types.F90
src/ccpp_types.meta

Support multiple concurrent instances per MPI task
closes #469
modified:   scripts/mkstatic.py
modified:   src/ccpp_types.F90
modified:   src/ccpp_types.meta
In order to have an ensemble of model instances in a JEDI executable, we
need for packages the model relies on to be “stateless” – meaning
that the data for an instances are not shared between instances. A more
comprehensive solution would be to implement physics so that all such
data is either passed in via arguments to the package, or allocated as
an instance of a class defining the physics.
Deferring the larger issue of revisiting CCPP requirements to cover
support for concurrent instances, this PR takes a more modest approach. It
adds a new "instance" dimension to the types already defined for GFS
physics (GFS_control, GFS_data, …

Support multiple concurrent instances per MPI task

---

scripts/mkstatic.py

When trying to update the latest UFS to use the latest CCPP framework hash, one of the regression tests using CMEPS uses a suite that doesn't have any schemes with a non-empty `init` phase. Due to this, the subroutine generated for the `init` phase in the cap doesn't have access to a ccpp_t instance. Yet, in mkstatic.py a line like `initialized({ccpp_var_name}%ccpp_instance) = .true.` is put in the subroutine regardless, resulting in a compilation error. 
A fix is to pass the ccpp_t_instance into the group cap for the `init` phase when it is otherwise empty so that `initialized({ccpp_var_name}%ccpp_instance) = .true.` has access to the ccpp_t_instance.
Fixes: No issue started
Testing:
test removed:
unit tests:
system tests: UFS RTs (re-running as of …

initialized_set_block bug fix

---

scripts/mkstatic.py

This PR is a bugfix for https://github.com/ufs-community/ccpp-physics/issues/127
https://github.com/NCAR/ccpp-framework/pull/503 was merged to fix the case when no scheme within a group has an init phase. A bug was introduced described in the ccpp-physics issue above. This fix ensures that the ccpp_t_instance variable is only passed once in the caps.
Fixes: 
https://github.com/ufs-community/ccpp-physics/issues/127
Testing:
test removed:
unit tests:
system tests: tested with UFS RTs 
[RegressionTests_hera.log](https://github.com/NCAR/ccpp-framework/files/13677899/RegressionTests_hera.log)
Note that the CMEPS tests are still passing in particular.
manual testing: Tested with the SCM using the SDF supplied in …

CCPP-physics Issue #127 Fix

---

scripts/common.py
scripts/mkstatic.py
src/ccpp_types.F90
src/ccpp_types.meta
test_prebuild/test_chunked_data/CMakeLists.txt
test_prebuild/test_chunked_data/README.md
test_prebuild/test_chunked_data/ccpp_prebuild_config.py
test_prebuild/test_chunked_data/chunked_data_scheme.F90
test_prebuild/test_chunked_data/chunked_data_scheme.meta
test_prebuild/test_chunked_data/data.F90
test_prebuild/test_chunked_data/data.meta
test_prebuild/test_chunked_data/main.F90
test_prebuild/test_chunked_data/suite_chunked_data_suite.xml

Add support for using chunked arrays to `ccpp_prebuild.py` while maintaining backward compatibility with the use of blocked data structures.
This PR adds support (and a test) for using chunked arrays as an alternative to blocked data structures to `ccpp_prebuild.py`. The idea behind this is that we can convert the ufs-weather-model to using contiguous arrays that are sent in chunks to the physics for (OpenMP-)parallel processing in the time integration (`run`) phase. The expectation is that this is at least as fast as the current implementation that uses blocked data structures (because the need to copy non-contiguous arrays into contiguous arrays and back for the `init`, `timestep_init`, `timestep_finalize` and `finalize` phases is removed). There is also evidence from extensive testing …

ccpp_prebuild.py: add support for chunked arrays

---

scripts/mkcap.py
scripts/mkstatic.py

Allocate dummy inactive local variables to size 0.
This is a temporary fix for the RRFS branch that is needed to compile with -check all. Using this flag, 
even if variables are not used within a scheme, they are checked for their allocation status, and 
unallocated variables lead to a runtime error. This fix goes with the other temporary fixes in 
ccpp-physics, fv3atm, etc. for the RRFS branch only. This issue is address more completely via 
https://github.com/NCAR/ccpp-framework/pull/529, and will be pulled into main when ready.
Fixes: temporarily addresses https://github.com/ufs-community/ufs-weather-model/issues/2023
Testing: 
test removed:
unit tests:
system tests: See https://github.com/ufs-community/ufs-weather-model/pull/2158 for testing results.
manual …

Dummy-allocate inactive local variables

---

scripts/ccpp_track_variables.py

Because of the change in directory structure for CCPP physics (https://github.com/ufs-community/ccpp-physics/pull/99), there are now `.meta` files at different levels in the directory tree. The `ccpp_track_variables.py` script needs the location of these `.meta` files as an input argument to the script, but the call to `glob.glob` in the script does not use the `recursive=True` argument, so even if the user passes in the argument `-m './physics/physics/**/'` (which should include all subdirectories), the call to `glob.glob` only searches one level. Our simple test case only has `.meta` files at a single directory level, so we never caught this issue.
Simply adding the `recursive=True` argument fixes this issue.
Fixes: #580 ccpp_track_variables.py is broken …

Fix for ccpp_track_variables.py: Need "recursive=True" for glob on .meta files

---

CMakeLists.txt

All in the title. Resolves https://github.com/NCAR/ccpp-framework/issues/610
Fixes: https://github.com/NCAR/ccpp-framework/issues/610
Testing: only CI testing needed
Related to https://github.com/NCAR/ccpp-physics/pull/1101

Update CMakeLists.txt: set minimum cmake version to 3.18

---

scripts/ccpp_prebuild.py
scripts/mkcap.py

**This PR affects ccpp-prebuild only. It can be merged into develop (or main), but it must come to main as soon as possible for use in UFS/SCM.**
This PR adds workarounds for handling optional arguments the right way (finally!) in `scripts/ccpp_prebuild.py` and `scripts/mkcap.py`. This update is already in use in NEPTUNE and is required for @dustinswales' work to update/revert the optional arguments in ccpp-physics in the UFS and the SCM.
The workaround for `ccpp-prebuild` allows us to treat only those arguments as optional that are truly optional for a CCPP scheme. In the past, any argument that was conditionally allocated by any of the host models had to be declared as optional, even if it was required by the physics.
User interface changes?: Yes and No. This can be merged without …

Merge two workarounds for ccpp-prebuild for handling optional arguments

---

scripts/ccpp_suite.py
test/var_compatibility_test/effr_calc.F90
test/var_compatibility_test/effr_calc.meta
test/var_compatibility_test/effr_diag.F90
test/var_compatibility_test/effr_diag.meta
test/var_compatibility_test/effr_post.F90
test/var_compatibility_test/effr_post.meta
test/var_compatibility_test/effr_pre.F90
test/var_compatibility_test/effr_pre.meta
test/var_compatibility_test/run_test
test/var_compatibility_test/test_host.F90
test/var_compatibility_test/test_host_data.F90
test/var_compatibility_test/test_host_data.meta
test/var_compatibility_test/test_reports.py

Description:
A python set is used to gather the schemes to call in the non CCPP run phases. However, python sets don't maintain the order, and hence the call order is wrong outside the run phase.
Fixes: #628 
Testing:
Expanded var_compatibility_test to have initialization phases and illustrate bug. 
Not sure how to test that the order is unchanged?

Capgen in SCM: Bug fix for scheme ordering in non-run phases

---

scripts/ccpp_prebuild.py
scripts/common.py
test/unit_tests/test_common.py

All in the title.
Closes https://github.com/NCAR/ccpp-framework/issues/641
Testing:
test removed: removed `test_execute` from `test/unit_tests/test_common.py`
unit tests: CI tests all pass
system tests: CI tests all pass
manual testing:
- tested with NEPTUNE
- ran `test_prebuild/run_all_tests.sh`

ccpp_prebuild.py: remove execute function from common.py, clean files the Python way
